package br.org.rosalina.social.auth;
import br.org.rosalina.social.audit.AuditService; import br.org.rosalina.social.common.ApiException; import br.org.rosalina.social.user.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/auth") public class AuthController {
 private final AppUserRepository users; private final PasswordEncoder encoder; private final JwtService jwt; private final AuditService audit;
 public AuthController(AppUserRepository u,PasswordEncoder e,JwtService j,AuditService a){users=u;encoder=e;jwt=j;audit=a;}
 public record LoginRequest(@NotBlank @Email String email,@NotBlank String password){} public record RefreshRequest(@NotBlank String refreshToken){} public record TokenResponse(String accessToken,String refreshToken,String tokenType){}
 @PostMapping("/login") TokenResponse login(@Valid @RequestBody LoginRequest r){AppUser u=users.findByEmailIgnoreCase(r.email()).filter(AppUser::isActive).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Credenciais inválidas."));if(!encoder.matches(r.password(),u.getPasswordHash()))throw new ApiException(HttpStatus.UNAUTHORIZED,"Credenciais inválidas.");audit.record("LOGIN","USER",u.getId());return new TokenResponse(jwt.access(u.getEmail(),u.getRole().name()),jwt.refresh(u.getEmail()),"Bearer");}
 @PostMapping("/refresh") TokenResponse refresh(@Valid @RequestBody RefreshRequest r){try{var c=jwt.parse(r.refreshToken());if(!"refresh".equals(c.get("type",String.class)))throw new IllegalArgumentException();AppUser u=users.findByEmailIgnoreCase(c.getSubject()).filter(AppUser::isActive).orElseThrow();return new TokenResponse(jwt.access(u.getEmail(),u.getRole().name()),jwt.refresh(u.getEmail()),"Bearer");}catch(Exception e){throw new ApiException(HttpStatus.UNAUTHORIZED,"Refresh token inválido.");}}
}
