package br.org.rosalina.social.student;
import br.org.rosalina.social.catalog.CatalogItem; import jakarta.persistence.*; import java.time.*; import java.util.*;
@Entity @Table(name="student") public class Student {
 @Id @GeneratedValue private UUID id; @Enumerated(EnumType.STRING) @Column(nullable=false) private StudentStatus status; @Column(nullable=false) private String name; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="activity_id",nullable=false) private CatalogItem activity; @Column(name="birth_date",nullable=false) private LocalDate birthDate;
 private String rg,cpf; private Boolean cadunico; private String nis; @Column(name="national_health_card") private String nationalHealthCard; private String address,neighborhood; @Column(name="reference_point") private String referencePoint; private String city; @Column(name="zip_code") private String zipCode; @Column(name="start_date") private LocalDate startDate; @Column(name="guardian_phone",nullable=false) private String guardianPhone; @Column(name="guardian_email") private String guardianEmail; @Column(name="student_phone") private String studentPhone; @Column(name="student_email") private String studentEmail; @Enumerated(EnumType.STRING) @Column(name="parents_relationship_status") private ParentsRelationshipStatus parentsRelationshipStatus;
 @OneToMany(mappedBy="student",cascade=CascadeType.ALL,orphanRemoval=true) private List<StudentRelative> relatives=new ArrayList<>(); @OneToOne(mappedBy="student",cascade=CascadeType.ALL,orphanRemoval=true) private SocioeconomicProfile socioeconomicProfile; @Column(name="created_at",nullable=false,updatable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
 @PrePersist void create(){createdAt=Instant.now();updatedAt=createdAt;} @PreUpdate void update(){updatedAt=Instant.now();}
 public UUID getId(){return id;} public StudentStatus getStatus(){return status;} public String getName(){return name;} public CatalogItem getActivity(){return activity;} public LocalDate getBirthDate(){return birthDate;} public String getRg(){return rg;} public String getCpf(){return cpf;} public Boolean getCadunico(){return cadunico;} public String getNis(){return nis;} public String getNationalHealthCard(){return nationalHealthCard;} public String getAddress(){return address;} public String getNeighborhood(){return neighborhood;} public String getReferencePoint(){return referencePoint;} public String getCity(){return city;} public String getZipCode(){return zipCode;} public LocalDate getStartDate(){return startDate;} public String getGuardianPhone(){return guardianPhone;} public String getGuardianEmail(){return guardianEmail;} public String getStudentPhone(){return studentPhone;} public String getStudentEmail(){return studentEmail;} public ParentsRelationshipStatus getParentsRelationshipStatus(){return parentsRelationshipStatus;} public List<StudentRelative> getRelatives(){return relatives;} public SocioeconomicProfile getSocioeconomicProfile(){return socioeconomicProfile;}
 public void setStatus(StudentStatus v){status=v;} public void setName(String v){name=v;} public void setActivity(CatalogItem v){activity=v;} public void setBirthDate(LocalDate v){birthDate=v;} public void setRg(String v){rg=v;} public void setCpf(String v){cpf=v;} public void setCadunico(Boolean v){cadunico=v;} public void setNis(String v){nis=v;} public void setNationalHealthCard(String v){nationalHealthCard=v;} public void setAddress(String v){address=v;} public void setNeighborhood(String v){neighborhood=v;} public void setReferencePoint(String v){referencePoint=v;} public void setCity(String v){city=v;} public void setZipCode(String v){zipCode=v;} public void setStartDate(LocalDate v){startDate=v;} public void setGuardianPhone(String v){guardianPhone=v;} public void setGuardianEmail(String v){guardianEmail=v;} public void setStudentPhone(String v){studentPhone=v;} public void setStudentEmail(String v){studentEmail=v;} public void setParentsRelationshipStatus(ParentsRelationshipStatus v){parentsRelationshipStatus=v;} public void setSocioeconomicProfile(SocioeconomicProfile v){socioeconomicProfile=v;if(v!=null)v.setStudent(this);}
 public void replaceRelatives(List<StudentRelative> values){relatives.clear(); if(values!=null)values.forEach(v->{v.setStudent(this);relatives.add(v);});}
}
